steps:
- step: Segmentation
  settings:
    model: yolo
    model_settings:
       model: Riksarkivet/yolov9-regions-1
    generation_settings:
       batch_size: 2
- step: Segmentation
  settings:
    model: yolo
    model_settings:
       model: Riksarkivet/yolov9-lines-within-regions-1
    generation_settings:
        batch_size: 2
- step: TextRecognition
  settings:
    model: WordLevelTrocr
    model_settings:
       model: Riksarkivet/trocr-base-handwritten-hist-swe-2
    generation_settings:
       batch_size: 4
       num_beams: 1
- step: ReadingOrderMarginalia
  settings:
    two_page: auto
- step: Export
  settings:
    dest: outputs/alto
    format: alto
- step: Export
  settings:
    dest: outputs/page
    format: page
labels:
  level_labels:
    - region
    - line
    - word
  sep: _
  template: "{label}{number}"