steps:
- step: Segmentation
  settings:
    model: yolo
    model_settings:
      model: Riksarkivet/yolov9-lines-within-regions-1
- step: TextRecognition
  settings:
    model: TrOCR
    model_settings:
      model: medieval-data/trocr-medieval-base
    generation_settings:
       batch_size: 16
- step: OrderLines